import { Role } from '@prisma/client';

const allRoles = {
  [Role.USER]: [
    'getProfile',
    'updateProfile',
    'getPreferences',
    'updatePreferences',
    'getPrivacySettings',
    'updatePrivacySettings',
    'getAccountStatus',
    'getUserStats',
    'getUserActivity',
    'getActivityStats',
    'getUserDevices',
    'getDeviceSessions',
    'trustDevice',
    'removeDevice',
    'removeAllOtherDevices',
    'getUserNotifications',
    'markNotificationAsRead',
    'markAllNotificationsAsRead',
    'deleteNotification',
    'deleteReadNotifications',
    'getNotificationStats',
    'getSecurityLogs',
    'getSecurityStats',
    'exportUserData',
    'deleteAccount',
    'uploadAvatar',
    'removeAvatar',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'regenerateBackupCodes',
  ],
  [Role.ADMIN]: [
    'getUsers',
    'manageUsers',
    'getUserProfile',
    'updateUserProfile',
    'getUserPreferences',
    'updateUserPreferences',
    'getPrivacySettings',
    'updatePrivacySettings',
    'getAccountStatus',
    'getUserStats',
    'getUserActivity',
    'getActivityStats',
    'getUserDevices',
    'getDeviceSessions',
    'trustDevice',
    'removeDevice',
    'removeAllOtherDevices',
    'getUserNotifications',
    'markNotificationAsRead',
    'markAllNotificationsAsRead',
    'deleteNotification',
    'deleteReadNotifications',
    'getNotificationStats',
    'getSecurityLogs',
    'getSecurityStats',
    'exportUserData',
    'deleteAccount',
    'uploadAvatar',
    'removeAvatar',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'regenerateBackupCodes',
    'getUsersWithExpiringPasswords',
    'getLockedUsers',
    'unlockUserAccount',
    'forcePasswordChange',
    'getDetailedHealthCheck',
    // ISP Management
    'viewISPDashboard',
    'manageCustomers',
    'deleteCustomer',
    'manageRouters',
    'deleteRouter',
    'managePackages',
    'deletePackage',
    'manageResellers',
    'deleteReseller',
    'manageInvoices',
    'manageTickets',
    'viewRouterLogs',
    // OLT Management
    'viewOltDashboard',
    'manageOlts',
    'deleteOlt',
    // Inventory Management
    'manageInventory',
    'deleteInventory',
    'managePurchaseOrders',
  ],
  [Role.SUPER_ADMIN]: [
    'getUsers',
    'manageUsers',
    'getUserProfile',
    'updateUserProfile',
    'getUserPreferences',
    'updateUserPreferences',
    'getPrivacySettings',
    'updatePrivacySettings',
    'getAccountStatus',
    'getUserStats',
    'getUserActivity',
    'getActivityStats',
    'getUserDevices',
    'getDeviceSessions',
    'trustDevice',
    'removeDevice',
    'removeAllOtherDevices',
    'getUserNotifications',
    'markNotificationAsRead',
    'markAllNotificationsAsRead',
    'deleteNotification',
    'deleteReadNotifications',
    'getNotificationStats',
    'getSecurityLogs',
    'getSecurityStats',
    'exportUserData',
    'deleteAccount',
    'uploadAvatar',
    'removeAvatar',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'regenerateBackupCodes',
    'getUsersWithExpiringPasswords',
    'getLockedUsers',
    'unlockUserAccount',
    'forcePasswordChange',
    'getDetailedHealthCheck',
    // ISP Management
    'viewISPDashboard',
    'manageCustomers',
    'deleteCustomer',
    'manageRouters',
    'deleteRouter',
    'managePackages',
    'deletePackage',
    'manageResellers',
    'deleteReseller',
    'manageInvoices',
    'manageTickets',
    'viewRouterLogs',
    // OLT Management
    'viewOltDashboard',
    'manageOlts',
    'deleteOlt',
    // Inventory Management
    'manageInventory',
    'deleteInventory',
    'managePurchaseOrders',
  ],
  [Role.MANAGER]: [
    'getProfile',
    'updateProfile',
    'getUserDevices',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'viewISPDashboard',
    'manageCustomers',
    'manageRouters',
    'managePackages',
    'manageResellers',
    'manageInvoices',
    'manageTickets',
    'viewRouterLogs',
    'viewOltDashboard',
    'manageOlts',
    'manageInventory',
    'managePurchaseOrders',
  ],
  [Role.SUPPORT]: [
    'getProfile',
    'updateProfile',
    'getUserDevices',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'viewISPDashboard',
    'manageCustomers',
    'manageTickets',
    'manageInvoices',
    'viewRouterLogs',
  ],
  [Role.FIELD_TECHNICIAN]: [
    'getProfile',
    'updateProfile',
    'getUserDevices',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'viewISPDashboard',
    'manageCustomers',
    'manageRouters',
    'viewRouterLogs',
    'viewOltDashboard',
    'manageOlts',
    'manageInventory',
  ],
  [Role.ENGINEER]: [
    'getProfile',
    'updateProfile',
    'getUserDevices',
    'setupTwoFactor',
    'enableTwoFactor',
    'disableTwoFactor',
    'getTwoFactorStatus',
    'viewISPDashboard',
    'manageCustomers',
    'manageRouters',
    'managePackages',
    'viewRouterLogs',
    'viewOltDashboard',
    'manageOlts',
    'manageInventory',
  ],
  [Role.RESELLER]: ['viewISPDashboard', 'manageCustomers', 'manageInvoices', 'manageTickets'],
  [Role.CUSTOMER]: ['viewISPDashboard'],
};

export const roles = Object.keys(allRoles);
export const roleRights = new Map(Object.entries(allRoles));

// Export roles object for use in routes
export { Role };
